FROM rcreasey/rpi-homebridge:base

RUN npm install -g https://github.com/rcreasey/homebridge-garage-sentry.git --unsafe-perm
RUN npm install -g homebridge-nest --unsafe-perm
RUN npm install -g homebridge-platform-ring-video-doorbell
